version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/home/breach/breach_harbor.db
      - JWT_SECRET=your_super_secure_jwt_secret_key_at_least_32_characters_long_12345
      - JWT_EXPIRY_MINUTES=60
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - MAXMIND_DB_PATH=./data/GeoLite2-City.mmdb
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080
      - LOG_LEVEL=info
    volumes:
      - ./data:/home/breach/data:ro
      - breach_data:/home/breach
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  breach_data:
    driver: local

networks:
  default:
    driver: bridge